package cipherGenerators.compare;

public class Comparer {
    public static double comparePlaintexts(String original, String decrypted) {

        if (original.length() != decrypted.length()) {
            throw new IllegalArgumentException("Texts dont have same length.");
        }

        int matches = 0;
        int length = original.length();

        StringBuilder diffLine = new StringBuilder();

        for (int i = 0; i < length; i++) {
            char o = original.charAt(i);
            char d = decrypted.charAt(i);

            if (o == d) {
                matches++;
                diffLine.append(" ");   // match
            } else {
                diffLine.append("^");   // diff
            }
        }

        double percent = 100.0 * matches / length;

        System.out.println("ORIGINAL :");
        System.out.println(original);

        System.out.println("DECRYPTED:");
        System.out.println(decrypted);

        System.out.println("DIFF     :");
        System.out.println(diffLine.toString());

        System.out.printf("Match: %.2f %% (%d / %d)%n", percent, matches, length);

        return percent;
    }

    static void main() {
//        String golden="THEQUICKBROWNFOXJUMPSOVERTHELAZYDOGANDTHENRUNSINTOFORESTWHEREITMEETSANOTHERFOXTHATTELLSASTRANGESTORYABOUTHIDDENTREASUREANDSECRETMAPSBURIEDUNDEROLDOAKTREES";
//        String pt="THEQUICKBROWNTOFJUMPSOVERTHELAYEDOGANDTHENRUNSINTOTORESTWHEREITMEETSANOTHERTOFTHATTELLSASTRANGESTOREABOUTHIDDENTREASUREANDSECRETMAPSBURIEDUNDEROLDOAKTREES";

//        String golden="THESUNROSEOVERTHEOLDCITYWALLSANDTHEMARKETPLACECAMEALIVEWITHTHESOUNDSOFVENDORSCALLINGOUTTHEIRPRICESFRESHFRUITSANDVEGETABLESWEREPILEDHIGHONCARTSWOODENCRATESOFAPPLESORANGESANDPEARSSATALONGSIDEBASKETSOFEGGSNEWLYBAKEDBREADFILLEDTHEAIRWITHARICHSCENTBUTTERSTILLGLISTENINGFROMTHECHURSTOODNEARTHEFOUNTAINWHEREWOMENHADGATHEREDTOFETCHTHEIRMORNINGWATERTHECHILDRENRANPASTLAUGHINGANDSHOUTINGWHILETHEIRPARENTSBARTEREDNOISILYWITHMERCHANTSWHOSESTALLSSTRETCHEDALONGTHENARROWCOBBLESTONESTREETANOLDMANWITHAGREYBEARDSATQUIETLYONASTONEBENCHNEARTHEENTRANCETOTHEMARKETPLACEHEWATCHEDTHEBUSLYCROWDWITHWISEYESANDSMILEDSOFTLY";
//        String pt="THESUNROSEOVERTHEOLDTITYWALLSANDTHEMARKETPLATETAMEALIVEWITHTHESOUNDSOFVENDORSTALLINGOUTTHEIRPRITESFRESHFRUITSANDVEGETABLESWEREPILEDHIGHONTARTSWOODENTRATESOFAPPLESORANGESANDPEARSSATALONGSIDEBASKETSOFEGGSNEWLYBAKEDBREADFILLEDTHEAIRWITHARITHSTENTBUTTERSTILLGLISTENINGFROMTHETHURSTOODNEARTHEFOUNTAINWHEREWOMENHADGATHEREDTOFETTHTHEIRMORNINGWATERTHETHILDRENRANPASTLAUGHINGANDSHOUTINGWHILETHEIRPARENTSBARTEREDNOISILYWITHMERTHANTSWHOSESTALLSSTRETTHEDALONGTHENARROWTOBBLESTONESTREETANOLDMANWITHAGREYBEARDSATCUIETLYONASTONEBENTHNEARTHEENTRANTETOTHEMARKETPLATEHEWATTHEDTHEBUSLYTROWDWITHWISEYESANDSMILEDSOFTLY";

        String golden="THESUNROSEOVERTHEOLDCITYWALLSANDTHEMARKETPLACECAMEALIVEWITHTHESOUNDSOFVENDORSCALLINGOUTTHEIRPRICESFRESHFRUITSANDVEGETABLESWEREPILEDHIGHONCARTSWOODENCRATESOFAPPLESORANGESANDPEARSSATALONGSIDEBASKETSOFEGGSNEWLYBAKEDBREADFILLEDTHEAIRWITHARICHSCENTBUTTERSTILLGLISTENINGFROMTHECHURSTOODNEARTHEFOUNTAINWHEREWOMENHADGATHEREDTOFETCHTHEIRMORNINGWATERTHECHILDRENRANPASTLAUGHINGANDSHOUTINGWHILETHEIRPARENTSBARTEREDNOISILYWITHMERCHANTSWHOSESTALLSSTRETCHEDALONGTHENARROWCOBBLESTONESTREETANOLDMANWITHAGREYBEARDSATQUIETLYONASTONEBENCHNEARTHEENTRANCETOTHEMARKETPLACEHEWATCHEDTHEBUSLYCROWDWITHWISEYESANDSMILEDSOFTLY";
        String pt="THESUNROSEOVERTHEOLDCITYRALLSANDTHEPARKETSLATETATEALIVERITHTHESOUNDSOFZENDORSTALLINGOUTTHEIRSRITESBRESHARUITSANDVEGETATLESTERESILEDHIGHONTARTSWOODENTRATESONASSLESORANGESANDSEARSSATALONGSIDETASKETSONEGGSNETLYTAKEDTREADFILLEDTHEAIRTITHARICHSCENTTUTTERSTILLGLISTENINGFROMTHETHURSTOODNEARTHEFOUNTAINTHERETOPENHADGATHEREDTOBETTHTHEIRJORNINGWATERTHETHILDRENRANSASTLAUGHINGANDSHOUTINGTHILETHEIRSARENTSTARTEREDNOISILYWITHTERTHANTSTHOSESTALLSSTRETTHEDALONGTHENARRORTOTTLESTONESTREETANOLDTANTITHAGREYTEARDSATQUIETLYONASTONETENTHNEARTHEENTRANTETOTHEMARKETSLATEHETATTHEDTHETUSLYCROWDWITHRISEYESANDSTILEDSOATLY";
        comparePlaintexts(golden, pt);
    }
}
